name: Build Image and Push to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-chronos:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-chronos:${{ github.sha }}


  build_self_hosted:
    runs-on:
      group: EC2
      labels: [self-hosted, deploy]
    
    needs: push_to_dockerhub
    
    steps:
    - name: Fix permissions
      run: |
        sudo chown -R $USER:$USER /home/ubuntu/shared-actions-runner/_work
        sudo chmod -R u+rw /home/ubuntu/shared-actions-runner/_work
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy application
      run: |
        docker stop swecc-server-chronos || true
        docker rm swecc-server-chronos || true
        
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/swecc-chronos:latest
        
        docker run -d --name swecc-server-chronos \
          --network swag-network \
          -v $(pwd):/app \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
          --restart unless-stopped \
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-chronos:latest
